<a href="https://colab.research.google.com/github/DawidSkowronski/PyTorch-Projects/blob/main/PyTorch_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Classification with DNN - Iris dataset

In [22]:
import torch
import torch.nn as nn
import torch.nn.functional as F

import matplotlib.pyplot as plt
%matplotlib inline

import pandas as pd

from sklearn.model_selection import train_test_split

In [23]:
# Loading data
url='https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv'

df = pd.read_csv(url)

In [24]:
df.head(3)

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa

In [25]:
# Change variety column from str to float
df['variety'] = df['variety'].replace('Setosa',0.0)
df['variety'] = df['variety'].replace('Versicolor',1.0)
df['variety'] = df['variety'].replace('Virginica',2.0)

/tmp/ipykernel_3275/2964742224.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['variety'] = df['variety'].replace('Virginica',2.0)

In [26]:
df.head(3)

   sepal.length  sepal.width  petal.length  petal.width  variety
0           5.1          3.5           1.4          0.2      0.0
1           4.9          3.0           1.4          0.2      0.0
2           4.7          3.2           1.3          0.2      0.0

In [27]:
# Train test Split

X = df.drop('variety', axis=1)
Y = df['variety']

# Convert X, Y to numpy arrays

X=X.values
Y=Y.values

In [31]:
# Train and test set split

X_train, X_test, Y_train, Y_test = train_test_split(X,Y,
                                                    train_size=0.8,
                                                    random_state=42)

In [28]:
# Model Class that inherits from nn.Module

class Model(nn.Module):
  # Input layer (4 characteristics of iris flower)
  # Hidden layer
  # Output layer (3 species of iris)

  # Number of neurons in each layer
  def __init__(self, input_number = 4,
               hidden1_number = 16,
               hidden2_number = 8,
               output_number = 3):
    super().__init__() # initiate nn.Module

  # fc - fully connected
    self.fc1 = nn.Linear(input_number, hidden1_number)
    self.fc2 = nn.Linear(hidden1_number, hidden2_number)
    self.out = nn.Linear(hidden2_number, output_number)

  # Forward propagation
  def forward(self, X):
    # Move data through layers
    X = F.relu(self.fc1(X))
    X = F.relu(self.fc2(X))
    X = F.relu(self.out(X))

    return X

In [29]:
# Set seed for repeatability
torch.manual_seed(42)

# Create instance of Model
model = Model()