<a href="https://colab.research.google.com/github/DawidSkowronski/PyTorch-Projects/blob/main/PyTorch_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Classification with DNN - Iris dataset

In [33]:
import torch
import torch.nn as nn
import torch.nn.functional as F

import matplotlib.pyplot as plt
%matplotlib inline

import pandas as pd
pd.set_option('future.no_silent_downcasting', True)

from sklearn.model_selection import train_test_split

In [34]:
# Loading data
url='https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv'

df = pd.read_csv(url)

In [35]:
df.head(3)

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa

In [58]:
# Change variety column from str to float
df['variety'] = df['variety'].replace({
    'Setosa': 0,
    'Versicolor': 1,
    'Virginica': 2
}).astype(int)

In [59]:
df

     sepal.length  sepal.width  petal.length  petal.width  variety
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

In [60]:
# Train test Split

X = df.drop('variety', axis=1)
Y = df['variety']

In [61]:
# Convert X, Y to numpy arrays
X=X.values
Y=Y.values

In [62]:
# Train and test set split

X_train, X_test, Y_train, Y_test = train_test_split(X,Y,
                                                    train_size=0.8,
                                                    random_state=42)

In [63]:
# Convert arrays to tensor
# X features to float tensors
X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)

# Y labels to tensors long (int)
Y_train = torch.LongTensor(Y_train)
Y_test = torch.LongTensor(Y_test)

# Creating the DNN model

In [73]:
# Model Class that inherits from nn.Module

class Model(nn.Module):
  # Input layer (4 characteristics of iris flower)
  # Hidden layer
  # Output layer (3 species of iris)

  # Number of neurons in each layer
  def __init__(self, input_number = 4,
               hidden1_number = 16,
               hidden2_number = 8,
               output_number = 3):
    super().__init__() # initiate nn.Module

  # fc - fully connected
    self.fc1 = nn.Linear(input_number, hidden1_number)
    self.fc2 = nn.Linear(hidden1_number, hidden2_number)
    self.out = nn.Linear(hidden2_number, output_number)

  # Forward propagation
  def forward(self, X):
    # Move data through layers
    X = F.relu(self.fc1(X))
    X = F.relu(self.fc2(X))
    X = F.relu(self.out(X))

    return X

In [74]:
# Set seed for repeatability
torch.manual_seed(42)

# Create instance of Model
model = Model()

In [75]:
# Criterion for model to measure prediction error
criterion = nn.CrossEntropyLoss()

# Adam Optimizer
optimizer = torch.optim.Adam(model.parameters(), lr = 0.001)

In [ ]:
# Epochs
epochs = 100

losses = []

for epoch in range(epochs):
  Y_predict = model.forward(X_train) # Get predicted results

  # Measure the error
  loss = criterion(Y_predict, Y_train)

  # History of losses
  losses.append(loss.detach().numpy())

  # Print progress
  if epoch % 10 ==0:
    print(f"Epoch: {epoch}, loss: {loss}")

  # Back propagation